<a href="https://colab.research.google.com/github/hamdirafi/DataMining/blob/main/Week5/Prakt-05_Jobsheet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Restaurant.csv to Restaurant.csv

In [3]:
import pandas as pd
restaurant = pd.read_csv("Restaurant.csv")
restaurant.head()

     BROOKLYN     Chinese    Z
0   MANHATTAN    American    C
1       BRONX     Chicken    C
2   MANHATTAN    American    A
3   MANHATTAN    American    A
4   MANHATTAN    American    C

In [7]:
restaurant = restaurant.replace("Yes", True)
restaurant = restaurant.replace("No", False)

restaurant = pd.get_dummies(restaurant)

In [9]:
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules

frequent_rest = fpgrowth(restaurant, min_support=0.05, use_colnames=True)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
rules_rest = association_rules(frequent_rest, metric="confidence", min_threshold=0.5)
rules_rest.sort_values('lift', ascending = False)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,( Chinese _ American ),( BROOKLYN _ MANHATTAN ),0.239164,0.412647,0.129867,0.543003,1.315904,1.0,0.031177,1.285246,0.315529,0.248814,0.221939,0.428860
3,"( Z_ A, Chinese _ American )",( BROOKLYN _ MANHATTAN ),0.134402,0.412647,0.072642,0.540487,1.309805,1.0,0.017182,1.278208,0.273253,0.153123,0.217655,0.358263
2,( Chinese _ American ),( Z_ A),0.239164,0.513081,0.134402,0.561963,1.095273,1.0,0.011691,1.111595,0.114329,0.217533,0.100392,0.411957
4,"( BROOKLYN _ MANHATTAN , Chinese _ American )",( Z_ A),0.129867,0.513081,0.072642,0.559359,1.090197,1.0,0.006010,1.105025,0.095083,0.127374,0.095043,0.350470
0,( BROOKLYN _ MANHATTAN ),( Z_ A),0.412647,0.513081,0.214806,0.520556,1.014568,1.0,0.003084,1.015591,0.024447,0.302151,0.015351,0.469607
5,( BROOKLYN _ BROOKLYN ),( Z_ A),0.232744,0.513081,0.116414,0.500179,0.974855,1.0,-0.003003,0.974188,-0.032525,0.184956,-0.026496,0.363535

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)